version: '3'
services:
  redis:
    build:
      context: .
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    expose:
      - "6379"
  rabbitmq:
    container_name: rabbitmq-stock
    image: rabbitmq
    ports:

      - "5672:5672"
    expose:
      - "5672"